// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Protocol_v3.proto</summary>
  public static partial class ProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90b2NvbF92My5wcm90bxIIcHJvdG9jb2wiSwoLUGFydGljaXBhbnQS",
            "CgoCaWQYASABKAMSEQoJZmlyc3ROYW1lGAIgASgJEhAKCGxhc3ROYW1lGAMg",
            "ASgJEgsKA2FnZRgEIAEoBSJfCghFbXBsb3llZRIKCgJpZBgBIAEoAxIQCgh1",
            "c2VybmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCRIRCglmaXJzdE5hbWUY",
            "BCABKAkSEAoIbGFzdE5hbWUYBSABKAkiyQIKCEFnZUV2ZW50EgoKAmlkGAEg",
            "ASgDEi0KCGFnZUdyb3VwGAIgASgOMhsucHJvdG9jb2wuQWdlRXZlbnQuQWdl",
            "R3JvdXASMwoLc3BvcnRzRXZlbnQYAyABKA4yHi5wcm90b2NvbC5BZ2VFdmVu",
            "dC5TcG9ydHNFdmVudCJjCghBZ2VHcm91cBIVChFVTktOT1dOX0FHRV9HUk9V",
            "UBAAEhMKD0dST1VQXzZfOF9ZRUFSUxABEhQKEEdST1VQXzlfMTFfWUVBUlMQ",
            "AhIVChFHUk9VUF8xMl8xNV9ZRUFSUxADImgKC1Nwb3J0c0V2ZW50EhgKFFVO",
            "S05PV05fU1BPUlRTX0VWRU5UEAASDQoJTUVURVJTXzUwEAESDgoKTUVURVJT",
            "XzEwMBACEg8KC01FVEVSU18xMDAwEAMSDwoLTUVURVJTXzE1MDAQBCKSAQoM",
            "UmVnaXN0cmF0aW9uEgoKAmlkGAEgASgDEioKC3BhcnRpY2lwYW50GAIgASgL",
            "MhUucHJvdG9jb2wuUGFydGljaXBhbnQSJAoIYWdlRXZlbnQYAyABKAsyEi5w",
            "cm90b2NvbC5BZ2VFdmVudBIkCghlbXBsb3llZRgEIAEoCzISLnByb3RvY29s",
            "LkVtcGxveWVlItYECgdSZXF1ZXN0EisKBHR5cGUYASABKA4yHS5wcm90b2Nv",
            "bC5SZXF1ZXN0LlJlcXVlc3RUeXBlEiYKCGVtcGxveWVlGAIgASgLMhIucHJv",
            "dG9jb2wuRW1wbG95ZWVIABIMCgJpZBgDIAEoA0gAEiYKCGFnZUV2ZW50GAQg",
            "ASgLMhIucHJvdG9jb2wuQWdlRXZlbnRIABIsCgtwYXJ0aWNpcGFudBgFIAEo",
            "CzIVLnByb3RvY29sLlBhcnRpY2lwYW50SAASLgoMcmVnaXN0cmF0aW9uGAYg",
            "ASgLMhYucHJvdG9jb2wuUmVnaXN0cmF0aW9uSAAi1gIKC1JlcXVlc3RUeXBl",
            "EhMKD1VOS05PV05fUkVRVUVTVBAAEgkKBUxPR0lOEAESCgoGTE9HT1VUEAIS",
            "FAoQQUREX1JFR0lTVFJBVElPThADEhMKD0FERF9QQVJUSUNJUEFOVBAEEg4K",
            "CkdFVF9FVkVOVFMQBRIUChBHRVRfUEFSVElDSVBBTlRTEAYSEwoPR0VUX1BB",
            "UlRJQ0lQQU5UEAcSEAoMR0VUX0VNUExPWUVFEAgSEQoNR0VUX0FHRV9FVkVO",
            "VBAJEh0KGVJFR0lTVFJBVElPTl9CWV9BR0VfRVZFTlQQChIfChtSRUdJU1RS",
            "QVRJT05fQllfUEFSVElDSVBBTlQQCxIfChtQQVJUSUNJUEFOVF9CWV9OQU1F",
            "X0FORF9BR0UQDBIWChJDT1VOVF9QQVJUSUNJUEFOVFMQDRIXChNDT1VOVF9S",
            "RUdJU1RSQVRJT05TEA5CCQoHcGF5bG9hZCL1AwoIUmVzcG9uc2USLQoEdHlw",
            "ZRgBIAEoDjIfLnByb3RvY29sLlJlc3BvbnNlLlJlc3BvbnNlVHlwZRIkCghl",
            "bXBsb3llZRgCIAEoCzISLnByb3RvY29sLkVtcGxveWVlEi0KDXJlZ2lzdHJh",
            "dGlvbnMYAyADKAsyFi5wcm90b2NvbC5SZWdpc3RyYXRpb24SKwoMcGFydGlj",
            "aXBhbnRzGAQgAygLMhUucHJvdG9jb2wuUGFydGljaXBhbnQSJQoJYWdlRXZl",
            "bnRzGAUgAygLMhIucHJvdG9jb2wuQWdlRXZlbnQSLAoMcmVnaXN0cmF0aW9u",
            "GAYgASgLMhYucHJvdG9jb2wuUmVnaXN0cmF0aW9uEioKC3BhcnRpY2lwYW50",
            "GAcgASgLMhUucHJvdG9jb2wuUGFydGljaXBhbnQSJAoIYWdlRXZlbnQYCCAB",
            "KAsyEi5wcm90b2NvbC5BZ2VFdmVudBINCgVjb3VudBgJIAEoBRINCgVlcnJv",
            "chgKIAEoCSJzCgxSZXNwb25zZVR5cGUSFAoQVU5LTk9XTl9SRVNQT05TRRAA",
            "EgYKAk9LEAESCQoFRVJST1IQAhIOCgpHRVRfRVZFTlRTEAMSFAoQR0VUX1BB",
            "UlRJQ0lQQU5UUxAEEhQKEE5FV19SRUdJU1RSQVRJT04QBUIdChBwcm90b2J1",
            "ZnByb3RvY29sQglQcm90b2J1ZnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Participant), global::Protocol.Participant.Parser, new[]{ "Id", "FirstName", "LastName", "Age" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Employee), global::Protocol.Employee.Parser, new[]{ "Id", "Username", "Password", "FirstName", "LastName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.AgeEvent), global::Protocol.AgeEvent.Parser, new[]{ "Id", "AgeGroup", "SportsEvent" }, null, new[]{ typeof(global::Protocol.AgeEvent.Types.AgeGroup), typeof(global::Protocol.AgeEvent.Types.SportsEvent) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Registration), global::Protocol.Registration.Parser, new[]{ "Id", "Participant", "AgeEvent", "Employee" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Request), global::Protocol.Request.Parser, new[]{ "Type", "Employee", "Id", "AgeEvent", "Participant", "Registration" }, new[]{ "Payload" }, new[]{ typeof(global::Protocol.Request.Types.RequestType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Response), global::Protocol.Response.Parser, new[]{ "Type", "Employee", "Registrations", "Participants", "AgeEvents", "Registration", "Participant", "AgeEvent", "Count", "Error" }, null, new[]{ typeof(global::Protocol.Response.Types.ResponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Participant : pb::IMessage<Participant>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Participant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant(Participant other) : this() {
      id_ = other.id_;
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      age_ = other.age_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant Clone() {
      return new Participant(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "firstName" field.</summary>
    public const int FirstNameFieldNumber = 2;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastName" field.</summary>
    public const int LastNameFieldNumber = 3;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 4;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Participant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Participant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      if (Age != other.Age) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Age);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LastName);
      }
      if (Age != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Age);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Participant other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            FirstName = input.ReadString();
            break;
          }
          case 26: {
            LastName = input.ReadString();
            break;
          }
          case 32: {
            Age = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            FirstName = input.ReadString();
            break;
          }
          case 26: {
            LastName = input.ReadString();
            break;
          }
          case 32: {
            Age = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Employee : pb::IMessage<Employee>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Employee> _parser = new pb::MessageParser<Employee>(() => new Employee());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Employee> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Employee() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Employee(Employee other) : this() {
      id_ = other.id_;
      username_ = other.username_;
      password_ = other.password_;
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Employee Clone() {
      return new Employee(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "firstName" field.</summary>
    public const int FirstNameFieldNumber = 4;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastName" field.</summary>
    public const int LastNameFieldNumber = 5;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Employee);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Employee other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(LastName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(LastName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Employee other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 34: {
            FirstName = input.ReadString();
            break;
          }
          case 42: {
            LastName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 34: {
            FirstName = input.ReadString();
            break;
          }
          case 42: {
            LastName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AgeEvent : pb::IMessage<AgeEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgeEvent> _parser = new pb::MessageParser<AgeEvent>(() => new AgeEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgeEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgeEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgeEvent(AgeEvent other) : this() {
      id_ = other.id_;
      ageGroup_ = other.ageGroup_;
      sportsEvent_ = other.sportsEvent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgeEvent Clone() {
      return new AgeEvent(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "ageGroup" field.</summary>
    public const int AgeGroupFieldNumber = 2;
    private global::Protocol.AgeEvent.Types.AgeGroup ageGroup_ = global::Protocol.AgeEvent.Types.AgeGroup.UnknownAgeGroup;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.AgeEvent.Types.AgeGroup AgeGroup {
      get { return ageGroup_; }
      set {
        ageGroup_ = value;
      }
    }

    /// <summary>Field number for the "sportsEvent" field.</summary>
    public const int SportsEventFieldNumber = 3;
    private global::Protocol.AgeEvent.Types.SportsEvent sportsEvent_ = global::Protocol.AgeEvent.Types.SportsEvent.UnknownSportsEvent;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.AgeEvent.Types.SportsEvent SportsEvent {
      get { return sportsEvent_; }
      set {
        sportsEvent_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgeEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgeEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (AgeGroup != other.AgeGroup) return false;
      if (SportsEvent != other.SportsEvent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (AgeGroup != global::Protocol.AgeEvent.Types.AgeGroup.UnknownAgeGroup) hash ^= AgeGroup.GetHashCode();
      if (SportsEvent != global::Protocol.AgeEvent.Types.SportsEvent.UnknownSportsEvent) hash ^= SportsEvent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (AgeGroup != global::Protocol.AgeEvent.Types.AgeGroup.UnknownAgeGroup) {
        output.WriteRawTag(16);
        output.WriteEnum((int) AgeGroup);
      }
      if (SportsEvent != global::Protocol.AgeEvent.Types.SportsEvent.UnknownSportsEvent) {
        output.WriteRawTag(24);
        output.WriteEnum((int) SportsEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (AgeGroup != global::Protocol.AgeEvent.Types.AgeGroup.UnknownAgeGroup) {
        output.WriteRawTag(16);
        output.WriteEnum((int) AgeGroup);
      }
      if (SportsEvent != global::Protocol.AgeEvent.Types.SportsEvent.UnknownSportsEvent) {
        output.WriteRawTag(24);
        output.WriteEnum((int) SportsEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (AgeGroup != global::Protocol.AgeEvent.Types.AgeGroup.UnknownAgeGroup) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AgeGroup);
      }
      if (SportsEvent != global::Protocol.AgeEvent.Types.SportsEvent.UnknownSportsEvent) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SportsEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgeEvent other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.AgeGroup != global::Protocol.AgeEvent.Types.AgeGroup.UnknownAgeGroup) {
        AgeGroup = other.AgeGroup;
      }
      if (other.SportsEvent != global::Protocol.AgeEvent.Types.SportsEvent.UnknownSportsEvent) {
        SportsEvent = other.SportsEvent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            AgeGroup = (global::Protocol.AgeEvent.Types.AgeGroup) input.ReadEnum();
            break;
          }
          case 24: {
            SportsEvent = (global::Protocol.AgeEvent.Types.SportsEvent) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            AgeGroup = (global::Protocol.AgeEvent.Types.AgeGroup) input.ReadEnum();
            break;
          }
          case 24: {
            SportsEvent = (global::Protocol.AgeEvent.Types.SportsEvent) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AgeEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum AgeGroup {
        [pbr::OriginalName("UNKNOWN_AGE_GROUP")] UnknownAgeGroup = 0,
        [pbr::OriginalName("GROUP_6_8_YEARS")] Group68Years = 1,
        [pbr::OriginalName("GROUP_9_11_YEARS")] Group911Years = 2,
        [pbr::OriginalName("GROUP_12_15_YEARS")] Group1215Years = 3,
      }

      public enum SportsEvent {
        [pbr::OriginalName("UNKNOWN_SPORTS_EVENT")] UnknownSportsEvent = 0,
        [pbr::OriginalName("METERS_50")] Meters50 = 1,
        [pbr::OriginalName("METERS_100")] Meters100 = 2,
        [pbr::OriginalName("METERS_1000")] Meters1000 = 3,
        [pbr::OriginalName("METERS_1500")] Meters1500 = 4,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Registration : pb::IMessage<Registration>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Registration> _parser = new pb::MessageParser<Registration>(() => new Registration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Registration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Registration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Registration(Registration other) : this() {
      id_ = other.id_;
      participant_ = other.participant_ != null ? other.participant_.Clone() : null;
      ageEvent_ = other.ageEvent_ != null ? other.ageEvent_.Clone() : null;
      employee_ = other.employee_ != null ? other.employee_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Registration Clone() {
      return new Registration(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 2;
    private global::Protocol.Participant participant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Participant Participant {
      get { return participant_; }
      set {
        participant_ = value;
      }
    }

    /// <summary>Field number for the "ageEvent" field.</summary>
    public const int AgeEventFieldNumber = 3;
    private global::Protocol.AgeEvent ageEvent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.AgeEvent AgeEvent {
      get { return ageEvent_; }
      set {
        ageEvent_ = value;
      }
    }

    /// <summary>Field number for the "employee" field.</summary>
    public const int EmployeeFieldNumber = 4;
    private global::Protocol.Employee employee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Employee Employee {
      get { return employee_; }
      set {
        employee_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Registration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Registration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(AgeEvent, other.AgeEvent)) return false;
      if (!object.Equals(Employee, other.Employee)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (participant_ != null) hash ^= Participant.GetHashCode();
      if (ageEvent_ != null) hash ^= AgeEvent.GetHashCode();
      if (employee_ != null) hash ^= Employee.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (participant_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Participant);
      }
      if (ageEvent_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AgeEvent);
      }
      if (employee_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Employee);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (participant_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Participant);
      }
      if (ageEvent_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AgeEvent);
      }
      if (employee_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Employee);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (participant_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (ageEvent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgeEvent);
      }
      if (employee_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Employee);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Registration other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.participant_ != null) {
        if (participant_ == null) {
          Participant = new global::Protocol.Participant();
        }
        Participant.MergeFrom(other.Participant);
      }
      if (other.ageEvent_ != null) {
        if (ageEvent_ == null) {
          AgeEvent = new global::Protocol.AgeEvent();
        }
        AgeEvent.MergeFrom(other.AgeEvent);
      }
      if (other.employee_ != null) {
        if (employee_ == null) {
          Employee = new global::Protocol.Employee();
        }
        Employee.MergeFrom(other.Employee);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (participant_ == null) {
              Participant = new global::Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 26: {
            if (ageEvent_ == null) {
              AgeEvent = new global::Protocol.AgeEvent();
            }
            input.ReadMessage(AgeEvent);
            break;
          }
          case 34: {
            if (employee_ == null) {
              Employee = new global::Protocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (participant_ == null) {
              Participant = new global::Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 26: {
            if (ageEvent_ == null) {
              AgeEvent = new global::Protocol.AgeEvent();
            }
            input.ReadMessage(AgeEvent);
            break;
          }
          case 34: {
            if (employee_ == null) {
              Employee = new global::Protocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Employee:
          Employee = other.Employee.Clone();
          break;
        case PayloadOneofCase.Id:
          Id = other.Id;
          break;
        case PayloadOneofCase.AgeEvent:
          AgeEvent = other.AgeEvent.Clone();
          break;
        case PayloadOneofCase.Participant:
          Participant = other.Participant.Clone();
          break;
        case PayloadOneofCase.Registration:
          Registration = other.Registration.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Protocol.Request.Types.RequestType type_ = global::Protocol.Request.Types.RequestType.UnknownRequest;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Request.Types.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "employee" field.</summary>
    public const int EmployeeFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Employee Employee {
      get { return payloadCase_ == PayloadOneofCase.Employee ? (global::Protocol.Employee) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Employee;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return HasId ? (long) payload_ : 0L; }
      set {
        payload_ = value;
        payloadCase_ = PayloadOneofCase.Id;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return payloadCase_ == PayloadOneofCase.Id; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      if (HasId) {
        ClearPayload();
      }
    }

    /// <summary>Field number for the "ageEvent" field.</summary>
    public const int AgeEventFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.AgeEvent AgeEvent {
      get { return payloadCase_ == PayloadOneofCase.AgeEvent ? (global::Protocol.AgeEvent) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.AgeEvent;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Participant Participant {
      get { return payloadCase_ == PayloadOneofCase.Participant ? (global::Protocol.Participant) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Participant;
      }
    }

    /// <summary>Field number for the "registration" field.</summary>
    public const int RegistrationFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Registration Registration {
      get { return payloadCase_ == PayloadOneofCase.Registration ? (global::Protocol.Registration) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Registration;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Employee = 2,
      Id = 3,
      AgeEvent = 4,
      Participant = 5,
      Registration = 6,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Employee, other.Employee)) return false;
      if (Id != other.Id) return false;
      if (!object.Equals(AgeEvent, other.AgeEvent)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(Registration, other.Registration)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Protocol.Request.Types.RequestType.UnknownRequest) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Employee) hash ^= Employee.GetHashCode();
      if (HasId) hash ^= Id.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.AgeEvent) hash ^= AgeEvent.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Participant) hash ^= Participant.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Registration) hash ^= Registration.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Protocol.Request.Types.RequestType.UnknownRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Employee) {
        output.WriteRawTag(18);
        output.WriteMessage(Employee);
      }
      if (HasId) {
        output.WriteRawTag(24);
        output.WriteInt64(Id);
      }
      if (payloadCase_ == PayloadOneofCase.AgeEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(AgeEvent);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(42);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.Registration) {
        output.WriteRawTag(50);
        output.WriteMessage(Registration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Protocol.Request.Types.RequestType.UnknownRequest) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Employee) {
        output.WriteRawTag(18);
        output.WriteMessage(Employee);
      }
      if (HasId) {
        output.WriteRawTag(24);
        output.WriteInt64(Id);
      }
      if (payloadCase_ == PayloadOneofCase.AgeEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(AgeEvent);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(42);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.Registration) {
        output.WriteRawTag(50);
        output.WriteMessage(Registration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Protocol.Request.Types.RequestType.UnknownRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Employee) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Employee);
      }
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (payloadCase_ == PayloadOneofCase.AgeEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgeEvent);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.Registration) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Registration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Protocol.Request.Types.RequestType.UnknownRequest) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Employee:
          if (Employee == null) {
            Employee = new global::Protocol.Employee();
          }
          Employee.MergeFrom(other.Employee);
          break;
        case PayloadOneofCase.Id:
          Id = other.Id;
          break;
        case PayloadOneofCase.AgeEvent:
          if (AgeEvent == null) {
            AgeEvent = new global::Protocol.AgeEvent();
          }
          AgeEvent.MergeFrom(other.AgeEvent);
          break;
        case PayloadOneofCase.Participant:
          if (Participant == null) {
            Participant = new global::Protocol.Participant();
          }
          Participant.MergeFrom(other.Participant);
          break;
        case PayloadOneofCase.Registration:
          if (Registration == null) {
            Registration = new global::Protocol.Registration();
          }
          Registration.MergeFrom(other.Registration);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Protocol.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Protocol.Employee subBuilder = new global::Protocol.Employee();
            if (payloadCase_ == PayloadOneofCase.Employee) {
              subBuilder.MergeFrom(Employee);
            }
            input.ReadMessage(subBuilder);
            Employee = subBuilder;
            break;
          }
          case 24: {
            Id = input.ReadInt64();
            break;
          }
          case 34: {
            global::Protocol.AgeEvent subBuilder = new global::Protocol.AgeEvent();
            if (payloadCase_ == PayloadOneofCase.AgeEvent) {
              subBuilder.MergeFrom(AgeEvent);
            }
            input.ReadMessage(subBuilder);
            AgeEvent = subBuilder;
            break;
          }
          case 42: {
            global::Protocol.Participant subBuilder = new global::Protocol.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 50: {
            global::Protocol.Registration subBuilder = new global::Protocol.Registration();
            if (payloadCase_ == PayloadOneofCase.Registration) {
              subBuilder.MergeFrom(Registration);
            }
            input.ReadMessage(subBuilder);
            Registration = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Protocol.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Protocol.Employee subBuilder = new global::Protocol.Employee();
            if (payloadCase_ == PayloadOneofCase.Employee) {
              subBuilder.MergeFrom(Employee);
            }
            input.ReadMessage(subBuilder);
            Employee = subBuilder;
            break;
          }
          case 24: {
            Id = input.ReadInt64();
            break;
          }
          case 34: {
            global::Protocol.AgeEvent subBuilder = new global::Protocol.AgeEvent();
            if (payloadCase_ == PayloadOneofCase.AgeEvent) {
              subBuilder.MergeFrom(AgeEvent);
            }
            input.ReadMessage(subBuilder);
            AgeEvent = subBuilder;
            break;
          }
          case 42: {
            global::Protocol.Participant subBuilder = new global::Protocol.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 50: {
            global::Protocol.Registration subBuilder = new global::Protocol.Registration();
            if (payloadCase_ == PayloadOneofCase.Registration) {
              subBuilder.MergeFrom(Registration);
            }
            input.ReadMessage(subBuilder);
            Registration = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("UNKNOWN_REQUEST")] UnknownRequest = 0,
        [pbr::OriginalName("LOGIN")] Login = 1,
        [pbr::OriginalName("LOGOUT")] Logout = 2,
        [pbr::OriginalName("ADD_REGISTRATION")] AddRegistration = 3,
        [pbr::OriginalName("ADD_PARTICIPANT")] AddParticipant = 4,
        [pbr::OriginalName("GET_EVENTS")] GetEvents = 5,
        [pbr::OriginalName("GET_PARTICIPANTS")] GetParticipants = 6,
        [pbr::OriginalName("GET_PARTICIPANT")] GetParticipant = 7,
        [pbr::OriginalName("GET_EMPLOYEE")] GetEmployee = 8,
        [pbr::OriginalName("GET_AGE_EVENT")] GetAgeEvent = 9,
        [pbr::OriginalName("REGISTRATION_BY_AGE_EVENT")] RegistrationByAgeEvent = 10,
        [pbr::OriginalName("REGISTRATION_BY_PARTICIPANT")] RegistrationByParticipant = 11,
        [pbr::OriginalName("PARTICIPANT_BY_NAME_AND_AGE")] ParticipantByNameAndAge = 12,
        [pbr::OriginalName("COUNT_PARTICIPANTS")] CountParticipants = 13,
        [pbr::OriginalName("COUNT_REGISTRATIONS")] CountRegistrations = 14,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      employee_ = other.employee_ != null ? other.employee_.Clone() : null;
      registrations_ = other.registrations_.Clone();
      participants_ = other.participants_.Clone();
      ageEvents_ = other.ageEvents_.Clone();
      registration_ = other.registration_ != null ? other.registration_.Clone() : null;
      participant_ = other.participant_ != null ? other.participant_.Clone() : null;
      ageEvent_ = other.ageEvent_ != null ? other.ageEvent_.Clone() : null;
      count_ = other.count_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Protocol.Response.Types.ResponseType type_ = global::Protocol.Response.Types.ResponseType.UnknownResponse;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Response.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "employee" field.</summary>
    public const int EmployeeFieldNumber = 2;
    private global::Protocol.Employee employee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Employee Employee {
      get { return employee_; }
      set {
        employee_ = value;
      }
    }

    /// <summary>Field number for the "registrations" field.</summary>
    public const int RegistrationsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Protocol.Registration> _repeated_registrations_codec
        = pb::FieldCodec.ForMessage(26, global::Protocol.Registration.Parser);
    private readonly pbc::RepeatedField<global::Protocol.Registration> registrations_ = new pbc::RepeatedField<global::Protocol.Registration>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Protocol.Registration> Registrations {
      get { return registrations_; }
    }

    /// <summary>Field number for the "participants" field.</summary>
    public const int ParticipantsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Protocol.Participant> _repeated_participants_codec
        = pb::FieldCodec.ForMessage(34, global::Protocol.Participant.Parser);
    private readonly pbc::RepeatedField<global::Protocol.Participant> participants_ = new pbc::RepeatedField<global::Protocol.Participant>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Protocol.Participant> Participants {
      get { return participants_; }
    }

    /// <summary>Field number for the "ageEvents" field.</summary>
    public const int AgeEventsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Protocol.AgeEvent> _repeated_ageEvents_codec
        = pb::FieldCodec.ForMessage(42, global::Protocol.AgeEvent.Parser);
    private readonly pbc::RepeatedField<global::Protocol.AgeEvent> ageEvents_ = new pbc::RepeatedField<global::Protocol.AgeEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Protocol.AgeEvent> AgeEvents {
      get { return ageEvents_; }
    }

    /// <summary>Field number for the "registration" field.</summary>
    public const int RegistrationFieldNumber = 6;
    private global::Protocol.Registration registration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Registration Registration {
      get { return registration_; }
      set {
        registration_ = value;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 7;
    private global::Protocol.Participant participant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.Participant Participant {
      get { return participant_; }
      set {
        participant_ = value;
      }
    }

    /// <summary>Field number for the "ageEvent" field.</summary>
    public const int AgeEventFieldNumber = 8;
    private global::Protocol.AgeEvent ageEvent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.AgeEvent AgeEvent {
      get { return ageEvent_; }
      set {
        ageEvent_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 9;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 10;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Employee, other.Employee)) return false;
      if(!registrations_.Equals(other.registrations_)) return false;
      if(!participants_.Equals(other.participants_)) return false;
      if(!ageEvents_.Equals(other.ageEvents_)) return false;
      if (!object.Equals(Registration, other.Registration)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(AgeEvent, other.AgeEvent)) return false;
      if (Count != other.Count) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Protocol.Response.Types.ResponseType.UnknownResponse) hash ^= Type.GetHashCode();
      if (employee_ != null) hash ^= Employee.GetHashCode();
      hash ^= registrations_.GetHashCode();
      hash ^= participants_.GetHashCode();
      hash ^= ageEvents_.GetHashCode();
      if (registration_ != null) hash ^= Registration.GetHashCode();
      if (participant_ != null) hash ^= Participant.GetHashCode();
      if (ageEvent_ != null) hash ^= AgeEvent.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Protocol.Response.Types.ResponseType.UnknownResponse) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (employee_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Employee);
      }
      registrations_.WriteTo(output, _repeated_registrations_codec);
      participants_.WriteTo(output, _repeated_participants_codec);
      ageEvents_.WriteTo(output, _repeated_ageEvents_codec);
      if (registration_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Registration);
      }
      if (participant_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Participant);
      }
      if (ageEvent_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(AgeEvent);
      }
      if (Count != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Count);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Protocol.Response.Types.ResponseType.UnknownResponse) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (employee_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Employee);
      }
      registrations_.WriteTo(ref output, _repeated_registrations_codec);
      participants_.WriteTo(ref output, _repeated_participants_codec);
      ageEvents_.WriteTo(ref output, _repeated_ageEvents_codec);
      if (registration_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Registration);
      }
      if (participant_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Participant);
      }
      if (ageEvent_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(AgeEvent);
      }
      if (Count != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Count);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Protocol.Response.Types.ResponseType.UnknownResponse) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (employee_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Employee);
      }
      size += registrations_.CalculateSize(_repeated_registrations_codec);
      size += participants_.CalculateSize(_repeated_participants_codec);
      size += ageEvents_.CalculateSize(_repeated_ageEvents_codec);
      if (registration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Registration);
      }
      if (participant_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (ageEvent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgeEvent);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Protocol.Response.Types.ResponseType.UnknownResponse) {
        Type = other.Type;
      }
      if (other.employee_ != null) {
        if (employee_ == null) {
          Employee = new global::Protocol.Employee();
        }
        Employee.MergeFrom(other.Employee);
      }
      registrations_.Add(other.registrations_);
      participants_.Add(other.participants_);
      ageEvents_.Add(other.ageEvents_);
      if (other.registration_ != null) {
        if (registration_ == null) {
          Registration = new global::Protocol.Registration();
        }
        Registration.MergeFrom(other.Registration);
      }
      if (other.participant_ != null) {
        if (participant_ == null) {
          Participant = new global::Protocol.Participant();
        }
        Participant.MergeFrom(other.Participant);
      }
      if (other.ageEvent_ != null) {
        if (ageEvent_ == null) {
          AgeEvent = new global::Protocol.AgeEvent();
        }
        AgeEvent.MergeFrom(other.AgeEvent);
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Protocol.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            if (employee_ == null) {
              Employee = new global::Protocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
          case 26: {
            registrations_.AddEntriesFrom(input, _repeated_registrations_codec);
            break;
          }
          case 34: {
            participants_.AddEntriesFrom(input, _repeated_participants_codec);
            break;
          }
          case 42: {
            ageEvents_.AddEntriesFrom(input, _repeated_ageEvents_codec);
            break;
          }
          case 50: {
            if (registration_ == null) {
              Registration = new global::Protocol.Registration();
            }
            input.ReadMessage(Registration);
            break;
          }
          case 58: {
            if (participant_ == null) {
              Participant = new global::Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 66: {
            if (ageEvent_ == null) {
              AgeEvent = new global::Protocol.AgeEvent();
            }
            input.ReadMessage(AgeEvent);
            break;
          }
          case 72: {
            Count = input.ReadInt32();
            break;
          }
          case 82: {
            Error = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Protocol.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            if (employee_ == null) {
              Employee = new global::Protocol.Employee();
            }
            input.ReadMessage(Employee);
            break;
          }
          case 26: {
            registrations_.AddEntriesFrom(ref input, _repeated_registrations_codec);
            break;
          }
          case 34: {
            participants_.AddEntriesFrom(ref input, _repeated_participants_codec);
            break;
          }
          case 42: {
            ageEvents_.AddEntriesFrom(ref input, _repeated_ageEvents_codec);
            break;
          }
          case 50: {
            if (registration_ == null) {
              Registration = new global::Protocol.Registration();
            }
            input.ReadMessage(Registration);
            break;
          }
          case 58: {
            if (participant_ == null) {
              Participant = new global::Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 66: {
            if (ageEvent_ == null) {
              AgeEvent = new global::Protocol.AgeEvent();
            }
            input.ReadMessage(AgeEvent);
            break;
          }
          case 72: {
            Count = input.ReadInt32();
            break;
          }
          case 82: {
            Error = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("UNKNOWN_RESPONSE")] UnknownResponse = 0,
        [pbr::OriginalName("OK")] Ok = 1,
        [pbr::OriginalName("ERROR")] Error = 2,
        [pbr::OriginalName("GET_EVENTS")] GetEvents = 3,
        [pbr::OriginalName("GET_PARTICIPANTS")] GetParticipants = 4,
        [pbr::OriginalName("NEW_REGISTRATION")] NewRegistration = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
